service:
  fullnameOverride: plsp-registryadapter
  namespace: nsptest
  replicaCount: 1

  ingress:
    enabled: false

  image:
    repository: plspregistry.azurecr.io/plspxdsadapter/xdsregistry
    tag: "1914"

  imagePullSecrets:
    - name: dockerplsp

  serviceAccount:
    create: false

  deployment:
    containerPort: 8080
    env: 
      backend_service_url:
        value: "https://reg-xds-api-edelivery-pilot.plsp.dk"
      homecommunity_id:
        value: "1.2.208.192.100"
      repository_unique_id:
        value: "1.2.3.4"
      typecode_code:
        value: "MedCom-OIOXML"
      typecode_text:
        value: "MedCom-OIOXML"
      typecode_scheme:
        value: "2.16.840.1.113883.6.1"
      classcode_code:
        value: "005"
      classcode_text:
        value: "Meddelelse"
      classcode_scheme:
        value: "1.2.208.184.100.9"
      formatcode_code:
        value: "uurn:ad:dk:medcom:message:full"
      formatcode_text:
        value: "dk:medcom:meddelelse"
      formatcode_scheme:
        value: "1.2.208.184.100.10"

  service:
    port: 80
    targetPort: container-port
