service:
  namespace: edelevery-sdn

  ingress:
    enabled: false

  image:
    repository: dockerregistry.hosting.kitkube.dk/plsp/plspxdsadapter/xdsregistry

  imagePullSecrets:
    - name: dockerplsp

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 160Mi