service:
  fullnameOverride: ap-ws2
  namespace: nsptest
  replicaCount: 1

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: ap-gateway.nsptest.medcom.dk
        paths:
          - path: /domibus
    tls:
      - hosts:
          - ap-gateway.nsptest.medcom.dk
        secretName: ap-gateway.nsptest.medcom.dk

  image:
    repository: localhost:30500/ap_ws
    tag: "2"

  serviceAccount:
    create: false
    
  initContainers:
    keystorebuilder:
      image:
        repository: "openjdk"
        tag: "11-jre-slim"
      commands:
          - bash
          - "-c"
          - "rm /output/domibus.jks; openssl pkcs12 -export -in /input/tls.crt -inkey /input/tls.key -name domibus -out my.p12 -password pass:Test1234; keytool -importkeystore -srckeystore my.p12 -srcstoretype pkcs12 -srcalias domibus -srcstorepass Test1234 -destkeystore /output/domibus.jks -deststoretype jks -deststorepass Test1234 -destalias \"medcom-edelivery-gateway (funktionscertifikat)\""
   
      extraVolumeMounts:
        keystore-dir:
          mountPath: /output
        input-keys:
          mountPath: /input
          
  deployment:
    containerPort: 8080
    configMapMountPaths:
        setenv.sh:
            configMapMountPath: /usr/local/tomcat/bin/setenv.sh
            configMapMountSubPath: setenv.sh
        domibus.properties:
            configMapMountPath: /usr/local/tomcat/domibus/domibus.properties
            configMapMountSubPath: domibus.properties
    hostAliases:
      212.98.96.26:
        - b-688bd8e9678ae0b24c1931eccf96d2d8.iso6523-actorid-upis.dk.acc.edelivery.tech.ec.europa.eu
        - b-5ad06aa330c02903faf9bd97421c7870.iso6523-actorid-upis.dk.acc.edelivery.tech.ec.europa.eu
        - b-5ad06aa330c02903faf9bd97421c7870.iso6523-actorid-upis3.dk.acc.edelivery.tech.ec.europa.eu
        
    extraVolumes:
      keystore-dir: |
        emptyDir: {}
      input-keys: |
        secret:
          secretName: ap-gateway
    extraVolumeMounts:
      keystore-dir:
        mountPath: /domibusconfig
        
  extraConfigMap:
    setenv.sh: |
        #!/bin/sh
        # Set CLASSPATH to include $CATALINA_HOME/domibus
        # where the domibus 'domibus.config.properties’ is located
        export CLASSPATH=$CATALINA_HOME/domibus
        export CATALINA_TMPDIR=$CATALINA_HOME/tmp
        export JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8 -Xms128m -Xmx1024m "
        export JAVA_OPTS="$JAVA_OPTS -Ddomibus.config.location=$CATALINA_HOME/domibus"
    domibus.properties: |
        domibus.UI.title.name=Domibus Medcom Gateway AP
        # ---------------------------------- Keystore/Truststore -----------------------

        domibus.security.keystore.location=${domibus.config.location}/keystores/cert_keystore.jks
        domibus.security.keystore.type=jks
        domibus.security.keystore.password=1

        domibus.security.key.private.alias=medcom-edelivery-gateway (funktionscertifikat)
        domibus.security.key.private.password=Test1234

        domibus.security.truststore.location=${domibus.config.location}/keystores/cert_truststore.jks
        domibus.security.truststore.type=jks
        domibus.security.truststore.password=1

        # ---------------------------------- Database ----------------------------------

        domibus.database.serverName=ap-db2
        domibus.database.port=3306
        domibus.database.schema=domibus_schema

        domibus.datasource.xa.xaDataSourceClassName=com.mysql.cj.jdbc.MysqlXADataSource
        domibus.datasource.xa.property.user=ap
        domibus.datasource.xa.property.password=mQuJZuxudsbdB2E
        domibus.datasource.xa.property.url=jdbc:mysql://${domibus.database.serverName}:${domibus.database.port}/${domibus.database.schema}?pinGlobalTxToPhysicalConnection=true

        domibus.datasource.driverClassName=com.mysql.cj.jdbc.Driver
        domibus.datasource.url=jdbc:mysql://${domibus.database.serverName}:${domibus.database.port}/${domibus.database.schema}?useSSL=false

        domibus.datasource.user=ap
        domibus.datasource.password=mQuJZuxudsbdB2E
        domibus.datasource.maxLifetime=30
        domibus.datasource.minPoolSize=5
        domibus.datasource.maxPoolSize=100

        # ---------------------------------- EntityManagerFactory ----------------------

        domibus.entityManagerFactory.jpaProperty.hibernate.connection.driver_class=com.mysql.cj.jdbc.MysqlXADataSource
        domibus.entityManagerFactory.jpaProperty.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
        domibus.entityManagerFactory.jpaProperty.hibernate.id.new_generator_mappings=false
        domibus.entityManagerFactory.jpaProperty.hibernate.format_sql=true
        domibus.entityManagerFactory.jpaProperty.hibernate.transaction.factory_class=org.hibernate.engine.transaction.internal.jta.CMTTransactionFactory
        domibus.entityManagerFactory.jpaProperty.hibernate.transaction.jta.platform=com.atomikos.icatch.jta.hibernate4.AtomikosJ2eePlatform

        # ---------------------------------- Dynamic Discovery -------------------------

        domibus.dynamicdiscovery.useDynamicDiscovery=true
        domibus.smlzone=dk.acc.edelivery.tech.ec.europa.eu
        domibus.dynamicdiscovery.client.specification=OASIS
        domibus.dynamicdiscovery.oasisclient.regexCertificateSubjectValidation=

        # ---------------------------------- ActiveMQ ----------------------------------

        activeMQ.broker.host=activemq
        activeMQ.brokerName=edelivery-mq
        activeMQ.JMXURL=service:jmx:rmi://${activeMQ.broker.host}:${activeMQ.rmiServerPort}/jndi/rmi://${activeMQ.broker.host}:${activeMQ.connectorPort}/jmxrmi
        activeMQ.connectorPort=1099
        activeMQ.rmiServerPort=1099
        activeMQ.transportConnector.uri=tcp://${activeMQ.broker.host}:61616
        activeMQ.username=system
        activeMQ.password=manager
  service:
    port: 8080
    targetPort: container-port
    
  certificate:
    ap-gateway.nsptest.medcom.dk:
      namespace: nsptest
      spec:
        secretName: ap-gateway.nsptest.medcom.dk
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
          group: cert-manager.io
        dnsNames:
          - ap-gateway.nsptest.medcom.dk
