service:
  namespace: edelevery-sdn

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: ap-gateway.nsptest.medcom.dk
        paths:
          - path: /domibus
    tls:
      - hosts:
          - ap-gateway.nsptest.medcom.dk
        secretName: ap-gateway.nsptest.medcom.dk

  image:
    repository: dockerregistry.t0.hosting.kitkube.dk/dockerhub/trifork/domibus

  initContainers:
    keystorebuilder:
      image:
        repository: dockerregistry.t0.hosting.kitkube.dk/dockerhub/library/openjdk
      resources:
        limits:
          cpu: 250m
          memory: 512Mi

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 2Gi

  certificate:
