mysql:
  namespace: "nsptest"
  fullnameOverride: "ap-db2"
  image:
    repository: "trifork/domibus-mysql"
    tag: "4.1.6"
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "applications"
      size: "1Gi"
  existingSecret: "ap-db-secret"
  db:
    user: "ap"
    name: "domibus_schema"

