mysql:
  namespace: edelevery-sdn
  image:
    repository: dockerregistry.hosting.kitkube.dk/dockerhub/trifork/domibus-mysql-4.2.5
  master:
    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    persistence:
      storageClass: longhorn

