service:
  namespace: edelevery-sdn

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: mq.edevlicery.dsdn.dk
        paths:
          - path:
    tls:
      - hosts:
          - mq.edevlicery.dsdn.dk
        secretName: star.edevlicery.dsdn.dk

  image:
    repository: dockerregistry.t0.hosting.kitkube.dk/dockerhub/trifork/activemq

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 200Mi

  certificate: