service:
  namespace: edelevery-sdn

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.100.0/24
    hosts:
      - host: mq.edelivery.dsdn.dk
        paths:
          - path: /
    tls:
      - hosts:
          - mq.edelivery.dsdn.dk
        secretName: star.edelivery.dsdn.dk

  image:
    repository: dockerregistry.hosting.kitkube.dk/dockerhub/trifork/activemq

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 200Mi

  certificate: