service:
  namespace: edelevery-sdn

  image:
    repository: dockerregistry.t0.hosting.kitkube.dk/plsp/plspxdsadapter/xdsrepository

  imagePullSecrets:
    - name: dockerplsp

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi