service:
  namespace: edelevery-sdn

  image:
    repository: dockerregistry.hosting.kitkube.dk/plsp/plspxdsadapter/xdsrepository

  imagePullSecrets:
    - name: dockerplsp

  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 180Mi