mysql:
  namespace: "nsptest"
  fullnameOverride: "db"
  image:
    registry: "localhost:30500"
    repository: "ap_db"
    tag: "2"
  replication:
    enabled: false
  master:
    persistence:
      enabled: false
  existingSecret: "ap-db-secret"
  db:
    user: "ap"
    name: "domibus_schema"

