mysql:
  namespace: "nsptest"
  fullnameOverride: "ap-db"
  image:
    repository: "trifork/domibus-mysql-4.1.6"
    tag: "1-cd64f7a"
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "applications"
      size: "10Gi"
      mountPath: "/var/lib/mysql"
  db:
    user: "ap"
    name: "domibus_schema"

