mysql:
  namespace: "nsptest"
  fullnameOverride: "db"
  image:
    registry: "localhost:30500"
    repository: "ap_db"
    tag: "2"
  replication:
    enabled: false
  master:
    persistence:
      enabled: false
  root:
    password: "kuk"
  db:
    user: "dsuser"
    password: "ds1234"
    name: "documentsources"

