mysql:
  namespace: "nsptest"
  fullnameOverride: "ap-db"
  image:
    registry: "localhost:30500"
    repository: "ap_db"
    tag: "2"
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: "applications"
      size: "10Gi"
      mountPath: "/var/lib/mysql"
  existingSecret: "ap-db-secret"
  db:
    user: "ap"
    name: "domibus_schema"

