service:
  namespace: edelevery-sdn

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: medcom-gateway.nsptest.medcom.dk
        paths:
          - path:
    tls:
      - hosts:
          - medcom-gateway.nsptest.medcom.dk
        secretName: medcom-gateway.nsptest.medcom.dk

  image:
    repository: dockerregistry.t0.hosting.kitkube.dk/dockerhub/trifork/medcom-gateway


  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 640Mi
      requests:
        cpu: 50m
        memory: 450Mi

  certificate:
