service:
  namespace: edelevery-sdn

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/whitelist-source-range: 195.80.245.2
    hosts:
      - host: medcom-gateway.edelivery.dsdn.dk
        paths:
          - path: /
    tls:
      - hosts:
          - medcom-gateway.edelivery.dsdn.dk
        secretName: star.edelivery.dsdn.dk

  image:
    repository: dockerregistry.hosting.kitkube.dk/dockerhub/trifork/medcom-gateway


  deployment:
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 300m
        memory: 2Gi

  certificate:
