service:
  fullnameOverride: medcom-gateway
  namespace: nsptest
  replicaCount: 0

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: medcom-gateway.nsptest.medcom.dk
        paths:
          - path: /repository
    tls:
      - hosts:
          - medcom-gateway.nsptest.medcom.dk
        secretName: medcom-gateway.nsptest.medcom.dk

  image:
    repository: trifork/medcom-gateway
    tag: "latest"

  serviceAccount:
    create: false

  env:
    - name: SERVER_PORT
      value: "8080"

  deployment:
    containerPort: 8080

  service:
    port: 8080
    targetPort: container-port

  certificate:
    medcom-gateway.nsptest.medcom.dk:
      namespace: nsptest
      spec:
        secretName: medcom-gateway.nsptest.medcom.dk
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
          group: cert-manager.io
        dnsNames:
          - medcom-gateway.nsptest.medcom.dk
