service:
  namespace: edelevery-sdn

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.100.0/24
    hosts:
      - host: medcom-gateway.edelivery.dsdn.dk
        paths:
          - path:
    tls:
      - hosts:
          - medcom-gateway.edelivery.dsdn.dk
        secretName: star.edelivery.dsdn.dk

  image:
    repository: dockerregistry.hosting.kitkube.dk/dockerhub/trifork/medcom-gateway


  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 640Mi
      requests:
        cpu: 50m
        memory: 450Mi

  certificate:
