service:
  fullnameOverride: medcom-gateway
  namespace: nsptest
  replicaCount: 1

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: medcom-gateway.nsptest.medcom.dk
        paths:
          - path: /repository
    tls:
      - hosts:
          - medcom-gateway.nsptest.medcom.dk
        secretName: medcom-gateway.nsptest.medcom.dk

  image:
    repository: trifork/medcom-gateway
    tag: "latest"

  serviceAccount:
    create: false
          
  deployment:
    containerPort: 8080

  service:
    port: 8080
    targetPort: container-port
