service:
  namespace: edelevery-sdn

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: medcom-gateway.edelivery.dsdn.dk
        paths:
          - path: /
    tls:
      - hosts:
          - medcom-gateway.edelivery.dsdn.dk
        secretName: star.edelivery.dsdn.dk

  image:
    repository: dockerregistry.hosting.kitkube.dk/dockerhub/trifork/medcom-gateway


  deployment:
    hostAliases:
      192.168.100.2:
        - "ap-dds.edelivery.dsdn.dk"
        - "ap-gateway.edelivery.dsdn.dk"
        - "dds-nsp.edelivery.dsdn.dk"
        - "nas2-nsp.edelivery.dsdn.dk"
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 300m
        memory: 2Gi

  certificate:
