mariadb:
  namespace: edelevery-sdn
  master:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 124Mi
    persistence:
      storageClass: longhorn
