apiVersion: v2
name: nsp-edelivery-applications-medcom
version: 1.0.0
dependencies:
  - name: argoApps
    version: 1.0.0
    repository: https://raw.githubusercontent.com/KvalitetsIT/helm-repo/main/
