argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/medcomdk/nsp-edelivery-k8s-services

  namespace: nsptest
  project: nsp-edelivery-medcom
  
  projects:
    nsp-edelivery-medcom:
      description: NSP eDelivery Test
      sources:
        - https://github.com/medcomdk/nsp-edelivery-k8s-services
      destinations:
        - namespace: nsptest
          server: https://kubernetes.default.svc
        - namespace: argo
          server: https://kubernetes.default.svc          
      ignored:
        - Secret
        - Role
        - RoleBinding
      warnignored: true

  applications:
    ap-db:
      path: ap-db
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-ws:
      path: ap-ws
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-db2:
      path: ap-db2
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-ws2:
      path: ap-ws2
      targetRevision: main
      valueFiles:
        - values.yaml

    medcom-gateway:
      path: medcom-gateway
      targetRevision: main
      valueFiles:
        - values.yaml

    activemq:
      path: mq
      targetRevision: main
      valueFiles:
        - values.yaml
