argoApps:
  server: https://kubernetes.default.svc
  repoUrl: git@github.com:medcomdk/nsp-edelivery-k8s-services.git

  namespace: nsptest
  project: nsp-edelivery-medcom
  
  projects:
    nsp-edelivery-medcom:
      description: NSP eDelivery Test
      sources:
        - git@github.com:medcomdk/nsp-edelivery-k8s-services.git
      destinations:
        - namespace: nsptest
          server: https://kubernetes.default.svc
        - namespace: argo
          server: https://kubernetes.default.svc          
      ignored:
        - Secret
        - Role
        - RoleBinding
      warnignored: true

  applications:
    plsp-registryadapter:
      path: plsp-registryadapter
      targetRevision: main
      valueFiles:
        - values.yaml

    plsp-repositoryadapter:
      path: plsp-repositoryadapter
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-db:
      path: ap-db
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-ws:
      path: ap-ws
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-db2:
      path: ap-db2
      targetRevision: main
      valueFiles:
        - values.yaml

    ap-ws2:
      path: ap-ws2
      targetRevision: main
      valueFiles:
        - values.yaml

    medcom-gateway:
      path: medcom-gateway
      targetRevision: main
      valueFiles:
        - values.yaml

    medcom-gateway-db:
      path: medcom-gateway-db
      targetRevision: main
      valueFiles:
        - values.yaml


    activemq:
      path: mq
      targetRevision: main
      valueFiles:
        - values.yaml
