apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "service.fullname" . }}-netpol
  namespace: {{ .Values.service.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ap-ws2
      app.kubernetes.io/name: service
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: mysql
            release: ap-db2
        namespaceSelector:
          matchLabels:
            name: edelevery-sdn
      ports:
        - protocol: TCP
          port: 3306
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      ports:
        - protocol: UDP
          port: 53
    - to:
      # DIGST/NetCompany
      - ipBlock:
          cidr: 80.198.95.43/32
        # Cert revoke list
      - ipBlock:
          cidr: 91.102.26.248/32
        #  http://ehealt-trackandtrace-pilot.azurewebsites.net/api/v1/Track
      - ipBlock:
          cidr: 40.127.192.244/32
      ports:
        - protocol: TCP
          port: 80
    - to:
      # SDN
      - ipBlock:
          cidr: 195.80.240.0/20
      - ipBlock:
          cidr: 192.168.100.0/24
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx
      ports:
      - protocol: TCP
        port: {{ .Values.service.deployment.containerPort }}
